version: '3.4'

services:
  broker:
    build:
      context: docker/kafka
      target: kafka
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9093:9093
      - 9094:9094
  zookeeper:
    build:
      context: docker/kafka
      target: zookeeper
    ports:
      - 2181:2181
