genitor:
  kafka:
    facts-topic:
      # Name of facts topic
      name: ${GENITOR_KAFKA_FACTS_TOPIC_NAME:facts}
      # Number of partitions of facts topic
      partitions: ${GENITOR_KAFKA_FACTS_TOPIC_PARTITIONS:1}
      # Number of replicas of facts topic
      replicas: ${GENITOR_KAFKA_FACTS_TOPIC_REPLICAS:1}
    ssl:
      # Path to Kafka keystore
      keystore: ${GENITOR_KAFKA_SSL_KEYSTORE}
      # Password of Kafka keystore
      keystore-password: ${GENITOR_KAFKA_SSL_KEYSTORE_PASSWORD}
      # Path to Kafka truststore
      truststore: ${GENITOR_KAFKA_SSL_TRUSTSTORE}
      # Password of Kafka truststore
      truststore-password: ${GENITOR_KAFKA_SSL_TRUSTSTORE_PASSWORD}

spring:
  kafka:
    bootstrap-servers: ${GENITOR_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    consumer:
      group-id: master
    ssl:
      key-store-location: file:${genitor.kafka.ssl.keystore}
      key-store-password: ${genitor.kafka.ssl.keystore-password}
      key-password: ${genitor.kafka.ssl.keystore-password}
      trust-store-location: file:${genitor.kafka.ssl.truststore}
      trust-store-password: ${genitor.kafka.ssl.truststore-password}
    properties:
      security.protocol: SSL
      ssl.protocol: SSL
      ssl.endpoint.identification.algorithm:
