genitor:
  # Path to deploy directory
  deploy-dir: ${GENITOR_DEPLOY_DIR:examples}
  server:
    # Server bind address
    bind-address: ${GENITOR_SERVER_BIND_ADDRESS:127.0.0.1}
    # Server bind port
    bind-port: ${GENITOR_SERVER_BIND_PORT:2001}
  db:
    # Host of PostgreSQL database
    host: ${GENITOR_DB_HOST:127.0.0.1}
    # Port of PostgreSQL database
    port: ${GENITOR_DB_PORT:5432}
    # Name of PostgreSQL database
    name: ${GENITOR_DB_NAME:genitor_master}
    # Username used to connect to PostgreSQL database
    username: ${GENITOR_DB_USERNAME:genitor_master}
    # Password used to connect to PostgreSQL database
    password: ${GENITOR_DB_PASSWORD:genitor_master}
  kafka:
    # Kafka servers comma-separated list
    bootstrap-servers: ${GENITOR_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    catalog-topic:
      # Name of catalog topic
      name: ${GENITOR_KAFKA_CATALOG_TOPIC_NAME:catalog}
      # Number of partitions of catalog topic
      partitions: ${GENITOR_KAFKA_CATALOG_TOPIC_PARTITIONS:1}
      # Number of replicas of catalog topic
      replicas: ${GENITOR_KAFKA_CATALOG_TOPIC_REPLICAS:1}
    facts-topic:
      # Name of facts topic
      name: ${GENITOR_KAFKA_FACTS_TOPIC_NAME:facts}
      # Number of partitions of facts topic
      partitions: ${GENITOR_KAFKA_FACTS_TOPIC_PARTITIONS:1}
      # Number of replicas of facts topic
      replicas: ${GENITOR_KAFKA_FACTS_TOPIC_REPLICAS:1}
    ssl:
      # Path to Kafka keystore
      keystore: ${GENITOR_KAFKA_SSL_KEYSTORE}
      # Password of Kafka keystore
      keystore-password: ${GENITOR_KAFKA_SSL_KEYSTORE_PASSWORD}
      # Path to Kafka truststore
      truststore: ${GENITOR_KAFKA_SSL_TRUSTSTORE}
      # Password of Kafka truststore
      truststore-password: ${GENITOR_KAFKA_SSL_TRUSTSTORE_PASSWORD}

server:
  address: ${genitor.server.bind-address}
  port: ${genitor.server.bind-port}

spring:
  datasource:
    url: jdbc:postgresql://${genitor.db.host}:${genitor.db.port}/${genitor.db.name}
    username: ${genitor.db.username}
    password: ${genitor.db.password}
  kafka:
    bootstrap-servers: ${genitor.kafka.bootstrap-servers}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: master
    ssl:
      key-store-location: file:${genitor.kafka.ssl.keystore}
      key-store-password: ${genitor.kafka.ssl.keystore-password}
      key-password: ${genitor.kafka.ssl.keystore-password}
      trust-store-location: file:${genitor.kafka.ssl.truststore}
      trust-store-password: ${genitor.kafka.ssl.truststore-password}
    properties:
      security.protocol: SSL
      ssl.protocol: SSL
      ssl.endpoint.identification.algorithm:
  liquibase:
    change-log: classpath:/db/changelog.yml
