genitor:
  # Hostname of this node
  hostname: ${GENITOR_HOSTNAME}
  # Number of minutes between two facts collection
  collect-facts-every: ${GENITOR_COLLECT_FACTS_EVERY:5}
  # Path to directory to save catalogs
  catalog-cache-dir: ${GENITOR_CATALOG_CACHE_DIR:~/.genitor/catalogs}
  server:
    # Server bind address
    bind-address: ${GENITOR_SERVER_BIND_ADDRESS:127.0.0.1}
    # Server bind port
    bind-port: ${GENITOR_SERVER_BIND_PORT:2010}
  kafka:
    # Kafka servers comma-separated list
    bootstrap-servers: ${GENITOR_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    # Name of catalog topic
    catalog-topic: ${GENITOR_KAFKA_CATALOG_TOPIC_NAME:catalog}
    # Name of facts topic
    facts-topic: ${GENITOR_KAFKA_FACTS_TOPIC_NAME:facts}
    ssl:
      # Path to Kafka keystore
      keystore: ${GENITOR_KAFKA_SSL_KEYSTORE}
      # Password of Kafka keystore
      keystore-password: ${GENITOR_KAFKA_SSL_KEYSTORE_PASSWORD}
      # Path to Kafka truststore
      truststore: ${GENITOR_KAFKA_SSL_TRUSTSTORE}
      # Password of Kafka truststore
      truststore-password: ${GENITOR_KAFKA_SSL_TRUSTSTORE_PASSWORD}

server:
  address: ${genitor.server.bind-address}
  port: ${genitor.server.bind-port}

spring:
  jackson:
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: ${genitor.kafka.bootstrap-servers}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${genitor.hostname}
    ssl:
      key-store-location: file:${genitor.kafka.ssl.keystore}
      key-store-password: ${genitor.kafka.ssl.keystore-password}
      key-password: ${genitor.kafka.ssl.keystore-password}
      trust-store-location: file:${genitor.kafka.ssl.truststore}
      trust-store-password: ${genitor.kafka.ssl.truststore-password}
    properties:
      security.protocol: SSL
      ssl.protocol: SSL
      ssl.endpoint.identification.algorithm:
